services:
  db:
    image: postgres:latest
    container_name: index
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: index
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres-data: null
